#ifndef BATTLE_DIALOGUE_H_
#define BATTLE_DIALOGUE_H_

#define DIALOGUE_FLOWEY0 0
#define DIALOGUE_FLOWEY1 1
#define DIALOGUE_FLOWEY2 2
#define DIALOGUE_FLOWEY3 3
#define DIALOGUE_FLOWEY4 4
#define DIALOGUE_FLOWEY5 5
#define DIALOGUE_FLOWEY6 6
#define DIALOGUE_FLOWEY7 7
#define DIALOGUE_FLOWEY8 8
#define DIALOGUE_FLOWEY9 9
#define DIALOGUE_FLOWEY10 10
#define DIALOGUE_FLOWEY11 11
#define DIALOGUE_FLOWEY12 12
#define DODGE_FLOWEY1 13
#define DODGE_FLOWEY2 14
#define DODGE_FLOWEY3 15
#define DODGE_FLOWEY4 16
#define DODGE_FLOWEY5 17
#endif
